package web

import (
	"bytes"
	"embed"
	"html/template"
	"mime"
	"net/http"
	"path"
	"strings"

	"github.com/pocketbase/pocketbase/core"
	"github.com/pocketbase/pocketbase/tools/router"

	"github.com/andrew-womeldorf/pbtest/internal/store"
)

//go:embed views
var viewsFS embed.FS

//go:embed static
var staticFS embed.FS

// staticHashes is defined in static_hashes.go, generated by: mise run web:hash

type Handler struct {
	app   core.App
	store store.Store
}

func RegisterRoutes(r *router.Router[*core.RequestEvent], app core.App, s store.Store) {
	h := &Handler{app: app, store: s}

	r.GET("/static/{path...}", serveStatic)

	r.GET("/login", h.loginPage)
	r.POST("/login", h.loginSubmit)
	r.GET("/register", h.registerPage)
	r.POST("/register", h.registerSubmit)
	r.POST("/logout", h.logout)

	auth := r.Group("").BindFunc(h.requireAuth)
	auth.GET("/books", h.listBooks)
	auth.GET("/books/new", h.newBook)
	auth.POST("/books/new", h.createBook)
	auth.GET("/books/{id}", h.showBook)
	auth.GET("/books/{id}/edit", h.editBook)
	auth.POST("/books/{id}/edit", h.updateBook)
	auth.POST("/books/{id}/delete", h.deleteBook)
	auth.POST("/books/{id}/publish", h.publishBook)
	auth.POST("/books/{id}/reviews", h.createReview)
	auth.POST("/reviews/{id}/delete", h.deleteReview)
}

func (h *Handler) requireAuth(e *core.RequestEvent) error {
	cookie, err := e.Request.Cookie("pb_auth")
	if err != nil || cookie.Value == "" {
		return e.Redirect(http.StatusFound, "/login")
	}

	record, err := h.app.FindAuthRecordByToken(cookie.Value, core.TokenTypeAuth)
	if err != nil {
		http.SetCookie(e.Response, &http.Cookie{
			Name:     "pb_auth",
			Value:    "",
			Path:     "/",
			MaxAge:   -1,
			HttpOnly: true,
			SameSite: http.SameSiteLaxMode,
		})
		return e.Redirect(http.StatusFound, "/login")
	}

	e.Set("userID", record.Id)
	e.Set("userName", record.GetString("name"))
	return e.Next()
}

type pageData map[string]any

func (h *Handler) render(e *core.RequestEvent, page string, data pageData) error {
	if data == nil {
		data = pageData{}
	}
	data["UserID"] = e.Get("userID")
	data["UserName"] = e.Get("userName")

	funcMap := template.FuncMap{
		"stars": func(rating int) string {
			return strings.Repeat("★", rating) + strings.Repeat("☆", 5-rating)
		},
		"staticPath": func(name string) string {
			if hash, ok := staticHashes[name]; ok {
				return "/static/" + name + "?" + hash
			}
			return "/static/" + name
		},
	}

	tmpl, err := template.New("layout.html").Funcs(funcMap).ParseFS(viewsFS, "views/layout.html", "views/"+page)
	if err != nil {
		return e.InternalServerError("", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return e.InternalServerError("", err)
	}

	return e.HTML(http.StatusOK, buf.String())
}

func (h *Handler) renderWithFlash(e *core.RequestEvent, page string, flash string, data pageData) error {
	if data == nil {
		data = pageData{}
	}
	data["Flash"] = flash
	return h.render(e, page, data)
}

func (h *Handler) userName(id string) string {
	if id == "" {
		return "Unknown"
	}
	record, err := h.app.FindRecordById("users", id)
	if err != nil {
		return "Unknown"
	}
	name := record.GetString("name")
	if name == "" {
		return record.GetString("email")
	}
	return name
}

var encodings = []struct {
	name string
	ext  string
}{
	{"br", ".br"},
	{"zstd", ".zst"},
	{"gzip", ".gz"},
}

func serveStatic(e *core.RequestEvent) error {
	reqPath := path.Clean(e.Request.PathValue("path"))
	if reqPath == "" || reqPath == "." || strings.HasPrefix(reqPath, "..") {
		return e.NotFoundError("", nil)
	}

	etag, ok := staticHashes[reqPath]
	if !ok {
		return e.NotFoundError("", nil)
	}
	etagHeader := `"` + etag + `"`

	if e.Request.Header.Get("If-None-Match") == etagHeader {
		e.Response.WriteHeader(http.StatusNotModified)
		return nil
	}

	accept := e.Request.Header.Get("Accept-Encoding")
	contentType := mime.TypeByExtension(path.Ext(reqPath))
	if contentType == "" {
		contentType = "application/octet-stream"
	}

	h := e.Response.Header()
	h.Set("Content-Type", contentType)
	h.Set("Cache-Control", "public, max-age=31536000, immutable")
	h.Set("ETag", etagHeader)
	h.Set("Vary", "Accept-Encoding")

	for _, enc := range encodings {
		if !acceptsEncoding(accept, enc.name) {
			continue
		}
		data, err := staticFS.ReadFile("static/" + reqPath + enc.ext)
		if err != nil {
			continue
		}
		h.Set("Content-Encoding", enc.name)
		_, _ = e.Response.Write(data)
		return nil
	}

	data, err := staticFS.ReadFile("static/" + reqPath)
	if err != nil {
		return e.NotFoundError("", nil)
	}
	_, _ = e.Response.Write(data)
	return nil
}

func acceptsEncoding(header, encoding string) bool {
	for _, part := range strings.Split(header, ",") {
		if strings.TrimSpace(strings.SplitN(part, ";", 2)[0]) == encoding {
			return true
		}
	}
	return false
}
