#!/usr/bin/env bash
#MISE description = "Generate static file content hashes"
#MISE hide = true
#MISE sources = ["internal/web/static/*.css"]

set -euo pipefail

STATIC_DIR="internal/web/static"
OUT="internal/web/static_hashes.go"

{
  echo "// Code generated by mise run web:hash. DO NOT EDIT."
  echo ""
  echo "package web"
  echo ""
  echo "var staticHashes = map[string]string{"

  find "$STATIC_DIR" -maxdepth 1 -type f \
    ! -name '*.gz' ! -name '*.br' ! -name '*.zst' \
    -print0 | sort -z | while IFS= read -r -d '' f; do
      name=$(basename "$f")
      hash=$(sha256sum "$f" | head -c 16)
      printf '\t"%s": "%s",\n' "$name" "$hash"
  done

  echo "}"
} > "$OUT"

gofmt -w "$OUT"
echo "hash: wrote $OUT"
